### ISSUE TITLE
Курсовой 9 семестр

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/bogachev-pa.github.io#1]
@aurusov
В эту таску буду выкладывать листы по курсовому и вопросы по ним.
Общий план:
1 - Постановка задачи А1
http://bogachev-pa.github.io/9_semester_work/1-initial-task-A1.pdf
2 - Диаграмма классов модуля вывода трассировочной информации - А1
http://bogachev-pa.github.io/9_semester_work/2-class-diagram-tracer-A1.pdf
3 - Диаграмма классов модуля конфигурации трассировки - А2
http://bogachev-pa.github.io/9_semester_work/3-class-diagram-trace-config-A2.pdf
4 - Диаграмма деятельности трассировщика - А1
http://bogachev-pa.github.io/9_semester_work/4-tracer-activity-diagram-A1.pdf
5 - Диаграмма состояний модуля конфигурации трассировки - А2
http://bogachev-pa.github.io/9_semester_work/5-trace-config-state-diagram-A2.pdf
6 - Диаграмма деятельности приведения номеров ресурсов в формат RAO-studio - А2
http://bogachev-pa.github.io/9_semester_work/6-activity-diagram-legacy-numbers.pdf
7 - Результаты работы - А1
http://bogachev-pa.github.io/9_semester_work/7-final-result-A1.pdf

Итого от 5.5 листов А1

Пояснительная записка:
http://bogachev-pa.github.io/9_semester_work/report.doc

Штампы 1 и 7 листов:
http://bogachev-pa.github.io/9_semester_work/1-7.pdf

Все листы одним файлом:
http://bogachev-pa.github.io/9_semester_work/all-combined.pdf

Исходники листов:
В .tar.gz: http://bogachev-pa.github.io/9_semester_work/results_raw.tar.gz
В .zip: http://bogachev-pa.github.io/9_semester_work/results_raw.zip

Результаты в целом тут:
http://bogachev-pa.github.io/

**Comment by bogachev-pa** [comment]
Сделал в черновом варианте.

> 3 - Диаграмма классов модуля конфигурации трассировки - А2

http://bogachev-pa.github.io/9_semester_work/class-diagram-trace-config-result-A2.pdf

Связи пока подписаны просто для общего представления, потом исправлю на более корректные.

Несколько вопросов по диаграммам классов вообще:
3: Многие мои классы имплементят библиотечные интерфейсы эклипса.
3:1. Нужно ли мне для этих интерфейсов наполнять тела или просто их обозначить, как я сделал сейчас?
3:2. Нужно ли мне прописывать все методы, которые мои классы оверрайдят (т.е. все методы интерфейса) или только те, в которых есть непустое содержимое?

**Comment by bogachev-pa** [comment]
> 2 - Диаграмма классов модуля вывода трассировки - А1

Сделал в получистовом варианте. Не подписаны связи, но в остальном почти готово.
http://bogachev-pa.github.io/9_semester_work/class-diagram-tracer-A1.pdf
Вопросы:
2:1. Tracer одновременно содержит `Subscriber`'ов и сам им является. Как лучше отобразить?
2:2. Tracer работает  с `Entry` из базы данных, надо ли отображать их на листе?
2:3. Нужно ли показывать для `LegacyTracer`'а все те же связи, что и для `Tracer`'а? Это сильно перегрузит диаграмму.

> 4 - Диаграмма деятельности трассировщика - А1

Сделал в черновом варианте.
http://bogachev-pa.github.io/9_semester_work/tracer-activity-A1.pdf

Проблемы/вопросы:
4:1. Главная проблема - диаграмма получается просто огромной, она не влезает на лист А1.
4:2. Надо ли подробно расписывать формирование строк? А формирование имен подобранных ресурсов (найти имя или записать тип[номер])?
4:3. Насколько подробно расписывать такие вещи как чтение параметров ресурсов/результатов разного вида?
4:4. Нужно ли чтение нескольких параметров объединять в блоки? Нужно ли указывать такие вещи как пропуск ненужных байт в `ByteBuffer`?

**Comment by bogachev-pa** [comment]
> 1 - Постановка задачи А1

В целом готово. Осталось вписать рабочее название нового РДО (я еще у Кирилла спросил его мнение) и я не уверен, как назвать то, что я сейчас назвал "Внешний вид".
http://bogachev-pa.github.io/9_semester_work/initial-task-A1.pdf

**Comment by aurusov** [comment]
По названию отписался в другой таске.
Очень много текста на листе, мало примеров. Текст по делу, поэтому можно оставить, но попытаться сделать больше размер. А вот с примерами надо переделать.
- От старой трассировки оставь буквально 5-10 строчек, сделай их намного большего размера, чтобы читалось. Кажется, что лучше оставить в цвете.
- Для новой подготовь аналогичные 5-10 строчек, того же размера и тоже цветную. Или ты специально хотел не показывать конечный результат на первом листе ?

**Comment by bogachev-pa** [comment]
> 6 - Диаграмма деятельности приведения номеров ресурсов в формат RAO-studio - А2

Сделал.
http://bogachev-pa.github.io/9_semester_work/6-result-activity-diagram-legacy-resources.pdf

Вопросов нет, мне лично она нравится.

**Comment by bogachev-pa** [comment]
> 2 - Диаграмма классов модуля вывода трассировочной информации - А1

Всё поправил, теперь в чистовом варианте.
http://bogachev-pa.github.io/9_semester_work/2-class-diagram-tracer-A1.pdf

> 3 - Диаграмма классов модуля конфигурации трассировки - А2

Всё поправил, теперь в чистовом варианте.
http://bogachev-pa.github.io/9_semester_work/3-class-diagram-trace-config-A2.pdf

**Comment by bogachev-pa** [comment]
> 5 - Диаграмма состояний модуля конфигурации трассировки - А2

Сделал.
http://bogachev-pa.github.io/9_semester_work/5-trace-config-state-diagram-A2.pdf

Вкратце, что осталось:
1 - Постановка задачи - поправить.
4 - Диаграмма деятельности трассировщика - переделать, чтобы вместилось на лист и было меньше лишнего.
7 - Результаты работы - сделать. Плюс, замеры скорости.
Ну и записка.

**Comment by bogachev-pa** [comment]
> 1 - Постановка задачи А1

Поправил.
http://bogachev-pa.github.io/9_semester_work/1-initial-task-A1.pdf

> Для новой подготовь аналогичные 5-10 строчек, того же размера и тоже цветную. Или ты специально хотел не показывать конечный результат на первом листе ?

Хотел только на листе результатов. Это же постановка задачи, вывода еще как бы нет.

**Comment by bogachev-pa** [comment]
> 7 - Результаты работы - А1

Сделал. Осталось только добавить на лист результаты по замерам скорости (я их еще не провел).
http://bogachev-pa.github.io/9_semester_work/7-final-results-A1.pdf

Еще немного поправил первый лист, чтобы не было повторений.

**Comment by bogachev-pa** [comment]
> 4 - Диаграмма деятельности трассировщика - А1

Переделал. На подпроцессы разбивать не стал, потому что не нашел выгоды в том плане, где их разместить. Кроме того, в ArgoUml их как-то не очень удобно делать, а другие средства начинать осваивать не хочется.
В целом, мне нравится, как выглядит лист.
http://bogachev-pa.github.io/9_semester_work/4-tracer-activity-diagram-A1.pdf

Собственно, с листами практически всё.
Осталось только добавить сравнение производительности на лист результатов, ну и записку доделать.

Все листы по порядку удобно смотреть в первом сообщении в этой таске.

**Comment by aurusov** [comment]
:one: `А1` Постановка задачи <b>[на печать]</b>
:two: `А1` Диаграмма классов модуля вывода трассировочной информации <b>[на печать]</b>
:three: `А2` Диаграмма классов модуля конфигурации трассировки <b>[на печать]</b>
:four: `А1` Диаграмма деятельности трассировщика <b>[на печать]</b>
:five: `А2` Диаграмма состояний модуля конфигурации трассировки <b>[на печать]</b>
:six: `A2` Диаграмма деятельности приведения номеров ресурсов в формат RAO-studio <b>[на печать]</b>
:seven: `А1` Результаты работы <b>[на печать]</b>
:eight: Штампы <b>[на печать]</b>
- лучше сделать на одном листе

**Comment by bogachev-pa** [comment]
> A?  Диаграмма деятельности приведения номеров ресурсов в формат RAO-studio
> Очень крупно. Почему не A3 ? Ты этот лист собираешься использовать в докладе, и важно, чтобы всё хорошо читалось ?

Размер шрифта такой же, как на листах 4 и 5. Может, просто кажется, что он крупный, потому что вертикальный? На А3 точно будет мелко.
В докладе собрался как минимум упомянуть, а если будут спрашивать что-то про легаси, то и рассказать.

> А1  Результаты работы
> Зачем два скрина ? Они очень похожи

В одном новый формат, он относится к пунктам "вывод трассировки" и "конфигурация трассировки", а в другой легаси формат, он относится к пункту "тестирование". 
Идея как раз в том, что там одни и те же записи, но в разных форматах.

**Comment by bogachev-pa** [comment]
> А2  Диаграмма классов модуля конфигурации трассировки
> С форматом А2 согласен. Попробуй увеличить размер шрифта, а то много белого на листе.

Поправил.
http://bogachev-pa.github.io/9_semester_work/3-class-diagram-trace-config-A2.pdf

> Штампы.

Залил.
http://bogachev-pa.github.io/9_semester_work/1.pdf
http://bogachev-pa.github.io/9_semester_work/7.pdf

> Нет результатов сравнения производительности

По замерам отписался в отдельной таске.
https://github.com/bogachev-pa/rdo-xtext/issues/12

**Comment by aurusov** [comment]
обновил статус листов

**Comment by bogachev-pa** [comment]
> Результаты работы

Переделал. Привел две диаграммы с замерами производительности. Числа использовал те, которые получил на данный момент.
http://bogachev-pa.github.io/9_semester_work/7-final-result-A1.pdf

Стиль оформления листа частично украл у Кирилла с его прошлого курсача, надеюсь, он не обидится.

**Comment by aurusov** [comment]
обновил статус листов, всё можно печатать

**Comment by bogachev-pa** [comment]
Залил финальные варианты всех листов и записки.
http://bogachev-pa.github.io/

**Comment by aurusov** [comment]
Сделай все листы со штампами одним файлом, как в примерах курсовых.

**Comment by bogachev-pa** [comment]
Сделал.
http://bogachev-pa.github.io/9_semester_work/all-combined.pdf

**Comment by aurusov** [comment]
Можешь выслать на почту или выложить на гитхаб исходники листов ?

**Comment by bogachev-pa** [comment]
Не очень понимаю, что считать исходниками листов? Диаграммы в форматах uml-средств и visio? Или отдельные svg диаграмм и рамок?

**Comment by aurusov** [comment]
Первое. То, что можно загрузить в редактор и подправить.

**Comment by bogachev-pa** [comment]
Залил.
В .tar.gz: http://bogachev-pa.github.io/9_semester_work/results_raw.tar.gz
В .zip: http://bogachev-pa.github.io/9_semester_work/results_raw.zip

**Comment by aurusov** [comment]
Выложил, спс.
