### ISSUE TITLE
Курсовой 10 семестр

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/bogachev-pa.github.io#2]
@aurusov
В эту таску буду выкладывать листы по курсовому и вопросы по ним.

Все листы одним файлом:
http://bogachev-pa.github.io/10_semester_work/all_in_one.pdf

Листы по отдельности:
1 - Постановка задачи А1
http://bogachev-pa.github.io/10_semester_work/1-initial-task.pdf
2 - Синтаксические диаграммы - А1
http://bogachev-pa.github.io/10_semester_work/2-syntax-diagram.pdf
3 - Синтаксические диаграммы - А1
http://bogachev-pa.github.io/10_semester_work/3-syntax-diagram.pdf
4 - Диаграмма классов подсистемы генерации кода - А1
http://bogachev-pa.github.io/10_semester_work/4-class-diagram.pdf
5 - Диаграмма деятельности валидации стандартных методов модели - А2
http://bogachev-pa.github.io/10_semester_work/5-activity-diagram.pdf
6 - Результаты работы - А1
http://bogachev-pa.github.io/10_semester_work/6-results.pdf
7 - Количественные показатели старой и новой грамматик - А3
http://bogachev-pa.github.io/10_semester_work/7-compare.pdf

Штампы для листов 1, 6, 7:
http://bogachev-pa.github.io/10_semester_work/1_6_7.pdf

Пояснительная записка:
http://bogachev-pa.github.io/10_semester_work/report.docx
В pdf:
http://bogachev-pa.github.io/10_semester_work/report.pdf

Исходники листов:
в tar.gz -http://bogachev-pa.github.io/10_semester_work/raw.tar.gz
в zip - http://bogachev-pa.github.io/10_semester_work/raw.zip

Итого 5 и 3/4 листов А1

Результаты в целом тут:
http://bogachev-pa.github.io/

**Comment by bogachev-pa** [comment]
@aurusov
Добавил листы 4 и 5.

5 готов, с ним все нормально.
Edit: нашел небольшой косяк: перед окончанием валидации нужно еще условие, что все методы проверены, и только тогда выходить. Вечером исправлю.

4 не закончен, потому что сейчас выглядит перегруженно, куча стрелочек и все пересекаются. Но, к сожалению, избавиться я от них никак не могу, я и так упростил связи между этими классами. Их можно немного разнести по краям листа, но глобально это положения не улучшит.

Вся проблема в большом количестве компайлеров (подо все: паттерны, ресурсы, последовательности и т.п.). Их все зовет генератор, чтобы сформировать `Java`-классы, а они все используют как минимум `RDOExpressionCompiler` для компиляции выражений, плюс еще некоторые классы. В итоге количество стрелочек выросло очень сильно.

Пока думаю, как бы ее улучшить.

**Comment by aurusov** [comment]
:one: Постановка задачи, А1 **[на печать]**
:two: Синтаксические диаграммы, А1 **[на печать]**
:three: Синтаксические диаграммы, А1 **[на печать]**
:four: Диаграмма классов подсистемы генерации кода, А1 **[на печать]**
:five: Диаграмма деятельности валидации стандартных методов модели, А2 **[на печать]**
:six: Результаты работы, А1 **[на печать]**
:seven: Сравнение размера моделей в старой и новой грамматике - А3 **[на печать]**
:eight: Штампы **[на печать]**

**Comment by bogachev-pa** [comment]
:one:
Добавил.
:four:
"Генерация кода" мне нравится больше. В записке тоже буду его придерживаться.
Диаграмму доделал.
:five:
Исправил.

**Comment by aurusov** [comment]
Всё хорошо, обновил итого

**Comment by bogachev-pa** [comment]
:two:, :three:
Готово.

**Comment by bogachev-pa** [comment]
Еще забыл обсудить название курсового. Я думаю, должно быть "Новая грамматика языка РДО".

**Comment by aurusov** [comment]
Тема подкупает простотой, давай оставим. Листы ok.

**Comment by bogachev-pa** [comment]
Залил пояснительную записку.

Все самое сложное там уже есть, в частности ТЗ и концептуальный этап.

Осталось сделать технический и рабочий этапы, опробирование и заключение.

**Comment by aurusov** [comment]
ТЗ
- По всем пунктам есть чем отчитаться о выполнении ?

> •    Несоответствие стилей разных компонентов языка.
> •    Перегруженность ключевыми словами.
> •    Слишком большой размер получающихся моделей.
> •    Несоответствие синтаксиса некоторых конструкций их смысловому содержанию.
> •    Большое количество искусственных ограничений.
- Про приемку не нашел. Или она где-то есть ? Напиши про сравнение результатов и трассировки моделей в старом и новом синтаксисе.

**Comment by bogachev-pa** [comment]
:six:
Залил лист результатов. Заметил, что поехали отступы, я исправлю.
По нему есть вопросы:
1. Не слишком ли мелкий шрифт примеров?
2. Я постарался уместить на лист примеры наиболее изменившихся компонентов, но все, естественно, не уместились. Достаточно ли этого или нужно что-то придумать? Просто может показаться, что я не все компоненты переправил, а только эти 5. Или достаточно сказать вслух?
3. Хочу еще разместить гистограммы сравнения размеров моделей. Думаю выделить под это отдельный лист А3. Нормально?

По ТЗ:

> По всем пунктам есть чем отчитаться о выполнении ?

Да, я их и писал в соответствии с тем, что было сделано.

> Про приемку не нашел. Или она где-то есть ? Напиши про сравнение результатов и трассировки моделей в старом и новом синтаксисе.

Пункт 3.7. Про результаты я там написал, а про трассировку не могу, потому что она частично сломалась.

**Comment by aurusov** [comment]
:six: 
- мелко, но смысл через объем передает, можно оставить
- достаточно
- да

ТЗ

> Пункт 3.7. Про результаты я там написал, а про трассировку не могу, потому что она частично сломалась.

Хорошо. Это раздел после моего замечания дописал или он раньше был ?

**Comment by bogachev-pa** [comment]
> Это раздел после моего замечания дописал или он раньше был ?

Хм, нет, он сразу был.

**Comment by aurusov** [comment]
> Хм, нет, он сразу был.

ok

Когда ждать остальные листы ?

**Comment by bogachev-pa** [comment]
:six:
Подровнял.
:seven:
Залил.

> Когда ждать остальные листы ?

Теперь залиты все.
Edit: забыл штампы, сейчас залью.

**Comment by bogachev-pa** [comment]
Залил штампы.

**Comment by aurusov** [comment]
:six:
Не заметил разницы. Поясни словами, чтобы было сделано. Выглядит нормально. Я бы немного вправо сдвинул левую часть. Много белого в середине.

**Comment by aurusov** [comment]
Отписался в итого

**Comment by bogachev-pa** [comment]
:six:

> Не заметил разницы. Поясни словами, чтобы было сделано.

Выровнял отступы между заголовками и текстом кусков модели.

> Я бы немного вправо сдвинул левую часть. Много белого в середине.

Готово.

:seven:
Формат А3. СМО поправил. Проценты в смысле насколько уменьшился размер моделей/грамматики? Если да, то тоже добавил.

**Comment by aurusov** [comment]
Хорошо, можно печатать и всё подписывать. Но перед защитой я хотел бы посмотреть всю записку.

**Comment by bogachev-pa** [comment]
У меня такой вопрос, а насколько уместно будет дать в записке ссылку на гитхаб?
Я бы хотел привести в записке полную грамматику языка (содержимое `RDO.xtext`), но даже без языка выражений она занимает 8 страниц, а это как-то слишком много для приложения (у меня там еще 4 страницы моделей).

Чтобы содержимое по ссылке не менялось это может быть, например, ссылка на файл на момент какого-то коммита (https://github.com/bogachev-pa/rdo-xtext/blob/65e3cf688841290b4e4030b228c4cedf26e54fed/ru.bmstu.rk9.rdo/src/ru/bmstu/rk9/rdo/RDO.xtext). Меня только удручает длина таких ссылок.

**Comment by aurusov** [comment]
Можно, но смотря где. Исходи из того, что читая бумажную записку, человек не обязан переходить по ссылке, чтобы понять смысл написанного. А как ссылка на приложение или ссылка в списке используемой литературы - ok.
Чтобы сократить ссылку воспользуйся https://goo.gl/
Твоя ссылка у меня превратилась в https://goo.gl/BJJck7

**Comment by bogachev-pa** [comment]
Залил записку в окончательном варианте.

**Comment by aurusov** [comment]
> Была написана документация по новой грамматике, включающая в себя руководство по изучению языка, а также формальную справку по синтаксису языка.

На всю граматику ?

**Comment by aurusov** [comment]
Чтобы выложить записку необходимо
- склеить все листы и штампы в один pdf
- выложить исходники листов

Пример идельного решения у Оли https://github.com/LeKaitoW/lekaitow.github.io/issues/1#issue-78248450

**Comment by bogachev-pa** [comment]
Все сделал, обновил первый пост.

**Comment by aurusov** [comment]
Спасибо, утащил http://aurusov.github.io/rdo_diploma/

**Comment by aurusov** [comment]
Закрывай таску
