### ISSUE TITLE
Дипломная работа

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/bogachev-pa.github.io#3]
1. **[Постановка задачи](http://bogachev-pa.github.io/diploma/1-%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B8-%D0%901.pdf)**. А1.
2. **[Дерево целей](http://bogachev-pa.github.io/diploma/2-%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE_%D1%86%D0%B5%D0%BB%D0%B5%D0%B9-A2.pdf)**. A2.
3. **[Диаграмма пакетов](http://bogachev-pa.github.io/diploma/3-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0_%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2-%D0%901.pdf)**. А1.
4. **[Синтаксическая диаграмма языка РДО](http://bogachev-pa.github.io/diploma/4-%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0_%D1%8F%D0%B7%D1%8B%D0%BA%D0%B0_%D1%80%D0%B4%D0%BE-%D0%901.pdf)**. А1.
5. **[Диаграмма классов подсистемы генерации и связывания кода](http://bogachev-pa.github.io/diploma/5-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0_%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%BE%D0%B2_%D0%BF%D0%BE%D0%B4%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D0%901.pdf)**. А1.
6. **[Диаграмма классов библиотеки моделирования](http://bogachev-pa.github.io/diploma/6-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0_%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%BE%D0%B2_%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%901.pdf)**. А1.
7. **[Диаграмма классов последовательностей](http://bogachev-pa.github.io/diploma/7-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0_%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%BE%D0%B2_%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B5%D0%B9-%D0%902.pdf)**. А2.
8. **[Диаграмма активности валидации стандартных методов модели](http://bogachev-pa.github.io/diploma/8-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0_%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D0%B8_%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%8B%D1%85_%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8-%D0%901.pdf)**. А1.
9. **[Диаграмма активности генерации и связывания кода точек принятия решений типа logic](http://bogachev-pa.github.io/diploma/9-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0_%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8_%D0%B8_%D1%81%D0%B2%D1%8F%D0%B7%D1%8B%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F_%D0%BA%D0%BE%D0%B4%D0%B0_logic-%D0%902.pdf)**. А2.
10. **[Диаграмма активности сборки и запуска модели](http://bogachev-pa.github.io/diploma/10-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0_%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B8_%D0%B8_%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8-%D0%901.pdf)**. А1.
11. **[Диаграмма последовательности вызовов компиляции и валидации модели](http://bogachev-pa.github.io/diploma/11-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0_%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B2%D1%8B%D0%B7%D0%BE%D0%B2%D0%BE%D0%B2_%D0%BA%D0%BE%D0%BC%D0%BF%D0%B8%D0%BB%D1%8F%D1%86%D0%B8%D0%B8_%D0%B8_%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D0%B8_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8-%D0%902.pdf)**. A2.
12. **[Исследование эффективности алгоритма копирования при записи](http://bogachev-pa.github.io/diploma/12_%D0%B8%D1%81%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D0%B0_%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F_%D0%BF%D1%80%D0%B8_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B8-%D0%902.pdf)**. А2.
13. **[Тестирование. Экранные формы](http://bogachev-pa.github.io/diploma/13-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%902.pdf)**. А2.
14. **[Функциональные возможности среды разработки моделей](http://bogachev-pa.github.io/diploma/14-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB_%D1%81%D1%80%D0%B5%D0%B4%D1%8B_%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B5%D0%B9-%D0%901.pdf)**. А1.
15. **[Результаты работы](http://bogachev-pa.github.io/diploma/15-%D1%80%D0%B5%D0%B7%D1%83%D0%BB%D1%8C%D1%82%D0%B0%D1%82%D1%8B_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D0%901.pdf)**. А1.

**[Штампы. Лист 1](http://bogachev-pa.github.io/diploma/%D0%A8%D1%82%D0%B0%D0%BC%D0%BF%D1%8B-1.pdf)**.
**[Штампы. Листы 12, 13, 14, 15](http://bogachev-pa.github.io/diploma/%D0%A8%D1%82%D0%B0%D0%BC%D0%BF%D1%8B-12-13-14-15.pdf)**.
**[Записка](http://bogachev-pa.github.io/diploma/%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%BA%D0%B0.pdf)**
**[Рецензия](http://bogachev-pa.github.io/diploma/%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F.pdf)**
**[Аннотация](http://bogachev-pa.github.io/diploma/%D0%B0%D0%BD%D0%BD%D0%BE%D1%82%D0%B0%D1%86%D0%B8%D1%8F.pdf)**
[Все листы одним файлом](http://bogachev-pa.github.io/diploma/all_in_one.pdf)
[Все вместе одним архивом, включая исходники](http://bogachev-pa.github.io/diploma/diploma.zip)

**Comment by bogachev-pa** [comment]
@aurusov
Выложил рецензию.

**Comment by aurusov** [comment]
Листы
1. Постановка задачи. А1, ok, **[на печать]**
2. Дерево целей. A2, ok, **[на печать]**
3. Диаграмма пакетов. А1, ok, **[на печать]**
4. Синтаксические диаграммы. А1 ok, **[на печать]**
5. Диаграмма классов подсистемы генерации и связывания кода. А1, ok, **[на печать]**
6. Диаграмма классов библиотеки моделирования. А1, ok, **[на печать]**
7. Диаграмма классов последовательностей. А2, ok, **[на печать]**
8. Диаграмма активности валидации стандартных методов модели. А1, ok, **[на печать]**
9. Диаграмма активности генерации и связывания кода точек принятия решений типа logic. А2, ok, **[на печать]**
10. Диаграмма активности сборки и запуска модели. А1, ok, **[на печать]**
11. Диаграмма последовательности вызовов компиляции и валидации модели. A2, ok, **[на печать]**
12. Исследование эффективности алгоритма копирования при записи. А2, ok, **[на печать]**
13. Тестирование. Экранные формы. А2, ok, **[на печать]**
14. Функциональные возможности среды разработки моделей. А1, ok, **[на печать]**
15. Результаты работы. А1, ok, **[на печать]**

Штампы, ok, **[на печать]**
Записка, ok, **[на печать]**
Рецензия, ok, **[на печать]**
Аннотация, ok, **[на печать]**

**Comment by bogachev-pa** [comment]
Все исправил.

>Каких ?

Например, нет параметров ресурсов по умолчанию. Добавил это в рецензию.

**Comment by aurusov** [comment]
- `возможностями, и включает` - запятая не нужна
- `в частности задания значений по умолчанию для параметров ресурсов` -> `, например, значения по умолчанию для параметров ресурсов`

**Comment by bogachev-pa** [comment]
Поправил.

**Comment by aurusov** [comment]
Давай удалим обсуждение резенции, что не мешало обсуждать листы

**Comment by bogachev-pa** [comment]
Добавил дерево целей.

**Comment by bogachev-pa** [comment]
Добавил диаграмму классов библиотеки моделирования.
Последовательности не влезли. Под них можно было бы выделить А2, но тогда получается суммарно 2.5 А1 на диаграммы классов. Это приемлемо?

UPD:
Добавил диаграмму классов подсистемы генерации и связывания кода.

**Comment by aurusov** [comment]
> Это приемлемо?

Не влезли на листы - ну и фиг с ними. В записку лучше добавить, если будут вопросы.

**Comment by bogachev-pa** [comment]
> Не влезли на листы - ну и фиг с ними. В записку лучше добавить, если будут вопросы.

Я пока еще не продумывал в окончательном варианте речь, но по моим текущим представлениям мне этот лист понадобился бы при рассказе. Потому что я хочу упомянуть, что последовательности теперь задаются не ключевыми словами, а предоставляются библиотекой моделирования, и сказать что иерархия классов последовательностей представлена на таком-то листе.

> Не жирно на А2 ?

Шрифт, по-моему, 24 или даже меньше. На А3 придется мельчить. Кроме того в большинстве старых дипломных проектов диаграммы целей такого (и часто меньшего) размера все на А2.

> на навигацию**<вот тут пропущен пробел>**по модели - если нет, то добейся еще большего отступа

Пропущен, поправлю.

**Comment by bogachev-pa** [comment]
Добавил синтаксическую диаграмму.

UPD: Исправил дерево целей.

**Comment by aurusov** [comment]
> Я пока еще не продумывал в окончательном варианте речь, но по моим текущим представлениям мне этот лист понадобился бы при рассказе. Потому что я хочу упомянуть, что последовательности теперь задаются не ключевыми словами, а предоставляются библиотекой моделирования, и сказать что иерархия классов последовательностей представлена на таком-то листе.

Если надо в докладе использовать, то лист с последовательностями _нужно_ делать. Другое дело, что и вылезать за 2хА1 тоже стремно. Коцать текущие диаграммы не хочется, но м.б. там есть что-то 'необязательное' ? Если нет, то делай 2.5хА1.

**Comment by aurusov** [comment]
Посмотрел

**Comment by bogachev-pa** [comment]
> Если надо в докладе использовать, то лист с последовательностями нужно делать. Другое дело, что и вылезать за 2хА1 тоже стремно. Коцать текущие диаграммы не хочется, но м.б. там есть что-то 'необязательное' ? Если нет, то делай 2.5хА1.

С текущих диаграмм убрать нечего, там все компоненты важные.

> DefaultMethod

Упустил. Добавлю.

> Не нашел XBlockExpression
> Не нашел JvmTypeReferece 

Это грамматические правила, предоставляемые Xbase. Решил их не показывать.

Еще раз перепроверю, что все на месте и поправлю.

**Comment by bogachev-pa** [comment]
Выложил записку.

В ней еще не доделаны некоторые моменты, которые я хотел бы сначала обсудить на консультации. Чего не хватает:
- нет реферата
- возможно, в концептуальной части нужно описать идею перехода на Xbase?
- возможно, в технической части нужен раздел про переход на Xbase?
- нужно добавить какое-то описание имплементации различных функций среды (автодополнение, форматирование), но непонятно, к техническому или к рабочему этапу это должно относиться
- не закончен один из пунктов исследовательской части - его особенно хочу обсудить на консультации
- нет заключения

UPD: обсудили все вопросы на консультации, сегодня поправлю записку соответствующим образом и залью исправления.

**Comment by bogachev-pa** [comment]
Исправлена записка (кроме исследовательской части - все еще доделываю ее).
Добавлены листы: 3 (диаграмма пакетов), 7 (диаграмма классов последовательностей), 8 (диаграмма активности валидации стандартных методов модели).
Исправлен лист 2 (дерево целей).

**Comment by aurusov** [comment]
> Исправлен лист 2 (дереве целей).

Стрелочки ?

**Comment by aurusov** [comment]
Посмотрел

**Comment by bogachev-pa** [comment]
> Стрелочки ?

Добавил стрелочки и рамку.

**Comment by bogachev-pa** [comment]
> **Диаграмма компонентов. А2**
> Много пустого места, прям совсем нечем забить ?

Вроде больше и нечем, я показал все пакеты в системе.
Попробую переставить что-то местами, мб.

> Какой размер у шрифта ? Не надо ли сделать А2

Шрифт 20. С 18 на А2 не влезает, я пробовал. Еще мельче делать и шрифт, и сами блоки пакетов не хочется.

> **Диаграмма активности валидации стандартных методов модели. А2**
> В штампе ошибка

Исправил.

**По записке:**

> Аннотация с каким-то комментарием

Не заполнено число страниц, т.к. еще изменится, когда в исследовательской части добавлю недостающий раздел. Поэтому место, куда надо будет вписать число страниц я пока отметил выделением.

> Сериализация в сокращениях есть, а десериализация ? Хотя не нашел этого термина в записке, но вдруг плохо искал

Использую термин "сериализация", когда говорю о тестировании и о посимвольном сравнении трассировки. "Десериализация" в записке не упоминается.

> ТЗ, требования. Слишком большой объем текста моделей. - надо переформулировать. Потому что объем зависит от задачи. Надо про упрощение синтаксических конструкций написать.

Исправил этот пункт на "громоздкие синтаксические конструкции". Так?

> ТЗ, требования. В выводах есть про тестирование. В требованиях не нашел.

Добавил.

> ТЗ, с обновление<пропущена_М>

Поправил.

> А что не так с исследованиями ? Она же на месте.

Раздел 6.3 не закончен (измерения в зависимости от размера поля). Плюс хочу добавить в записку графики.

> Выводы. Выявлены ключевые классы - Спроектированы же, не ?

Согласен, поправил.

**Comment by aurusov** [comment]
> Попробую переставить что-то местами, мб.

Забей

**Comment by aurusov** [comment]
> Исправил этот пункт на "громоздкие синтаксические конструкции". Так?

Норм

**Comment by aurusov** [comment]
Посмотрел

**Comment by bogachev-pa** [comment]
Добавил лист с исследовательской частью и закончил записку.

По вашему совету провел измерения с большим объемом памяти, выделяемому jvm. В итоге алгоритм глубокого копирования умирает за разумное время только на очень большом поле и размере фишки (например 64x64, 512 байт). Отображать это на графиках мне показалось неинтересным, в итоге я вообще убрал эту часть. Вместо этого сделал 2 пары гистограмм от размера поля и от размера параметров фишки.
На одной значения числа порожденных вершин, а на другой соотношение для обоих алгоритмов.

Насчет нумерации - перед этим листом по смыслу будут еще, но выложу их чуть позже. Мне в таске нумеровать их так, как должны быть по смыслу, или продолжать текущую нумерацию?

**Comment by aurusov** [comment]
> Мне в таске нумеровать их так, как должны быть по смыслу, или продолжать текущую нумерацию?

Лучше перенумеровать. И в твоем списке и в моём, но только когда отпишусь, что посмотрел.

**Comment by aurusov** [comment]
> В итоге алгоритм глубокого копирования умирает за разумное время только на очень большом поле и размере фишки (например 64x64, 512 байт).

Именно это видно на левом верхнем ?

**Comment by aurusov** [comment]
Посмотрел

**Comment by bogachev-pa** [comment]
> Именно это видно на левом верхнем ?

Там видно серьезное проседание по производительности, но по памяти ни один из алгоритмов еще не умирает. Для этого надо сделать и большой размер поля, и большой размер фишки. Я на гистограммах увеличивал их по отдельности.

**Comment by aurusov** [comment]
Ага. Т.е. это кол-во порожденных вершин за фиксированное время ? Отрази это в названии графика или оси ординат.

**Comment by aurusov** [comment]
А при каких условиях алгоритмы валятся по памяти ? Насколько лучше cow ?

**Comment by bogachev-pa** [comment]
> Ага. Т.е. это кол-во порожденных вершин за фиксированное время ? Отрази это в названии графика или оси ординат.

Отразил. Заодно поправил название оси ординат на нижних графиках, теперь назвал "прирост производительности" вместо "соотношение", кажется, так правильнее.

> А при каких условиях алгоритмы валятся по памяти ? Насколько лучше cow ?

Если выделить jvm 4 гб памяти (без возможности доаллоцировать, т.е. 4 и старт и предел), то старый алгоритм на конфигурации 64x64 512 байт умирает примерно через 100 секунд.
Если выделить jvm 1 гб памяти, то при такой же конфигурации старый алгоритм умирает примерно за 30-40 секунд.

Добиться того, чтобы cow умер по памяти у меня не вышло на такой конфигурации, более 500 секунд от отработал нормально даже с 1гб доступной памяти. Можно попробовать сделать совсем большие поля и фишки, если хотим увидеть его предел.

> Записка

Все поправил.

**Comment by aurusov** [comment]
> Добиться того, чтобы cow умер по памяти у меня не вышло на такой конфигурации, более 500 секунд от отработал нормально даже с 1гб доступной памяти. Можно попробовать сделать совсем большие поля и фишки, если хотим увидеть его предел.

Ого. Мне даже интересно стало. После листов, но до защиты хотелось бы узнать его предел.

> Все поправил.

Посмотрел, норм.

**Comment by bogachev-pa** [comment]
Добавил потерянный `DefaultMethod` в синтаксическую диаграмму.

> Ого. Мне даже интересно стало. После листов, но до защиты хотелось бы узнать его предел.

Ок.

**Comment by aurusov** [comment]
Посмотрел

**Comment by bogachev-pa** [comment]
Добавил диаграмму активности генерации и связывания кода точек принятия решений типа logic.

**Comment by aurusov** [comment]
Походу из-за копипасты поехал размер листов

**Comment by bogachev-pa** [comment]
Нет, все в порядке. Все листы, про которые вы спрашиваете, и должны быть А2.

**Comment by bogachev-pa** [comment]
Добавил диаграмму активности сборки и запуска модели. (А1)
Добавил лист по тестированию (экранные формы). (А2)
Добавил диаграмму последовательности вызовов компиляции и валидации модели. (А2)

**Comment by aurusov** [comment]
Посмотрел

**Comment by bogachev-pa** [comment]
Добавил лист постановки задачи.

> **Диаграмма последовательности вызовов компиляции и валидации модели.**
> что означают крестики на пересечении ?

Окончание времени жизни объектов.

**Comment by aurusov** [comment]
Посмотрел

**Comment by bogachev-pa** [comment]
> **Постановка задачи. А1**
> 
> Что хотел показать скрином ? Как будешь его использовать ? Пример code-complete с Местоположение важен ?

Просто скрин существующей системы. Для доклада пример не важен, но в случае вопросов могу показать, что существовал некоторый частичный code-complete для отдельных случаев, и что он был расширен и обобщен.

> Что значит Исследование новых технологий ? Звучит как самоцель проекта.

Заменил на "использование". Кажется, так лучше?

> **Тестирование. Экранные формы. А2**

Все исправил. На нижнем скрине везде использовал существительные.

**Comment by aurusov** [comment]
> Для доклада пример не важен, но в случае вопросов могу показать, что существовал некоторый частичный code-complete для отдельных случаев, и что он был расширен и обобщен.

Как ты его покажешь ? Я то думал, что ты хотел этот скрин так использовать, присмотрелся - а там норм дополнение.

> Заменил на "использование". Кажется, так лучше?

Конечно

**Comment by aurusov** [comment]
Посмотрел

**Comment by bogachev-pa** [comment]
> **Тестирование. Экранные формы.**
> нижний
> Что-то забыл сразу спросить - а почему не хочешь показать верхную часть web-страницы ? Там же слева красивые картиночки, история успешных и не очень запусков.

Имеете ввиду [главную страницу](http://jenkins.raox.rk9.bmstu.ru/)?
Но так ведь не будет видно отчета тестирования. Я понимаю, что там все равно довольно мелкий текст, но сам факт того, что отчет там присутствует, наверное, заметен.

> Как ты его покажешь ? Я то думал, что ты хотел этот скрин так использовать, присмотрелся - а там норм дополнение.

Можно на листе результатов работы показать два примера автодополнения. Аналогичный данному и какой-то еще другой. Сейчас выложил этот лист в черновом варианте (что бы был виден пример, как я там показываю автодополнение).

UPD: осознал, что "средства среды" звучит не очень - переименую в "функционал среды разработки моделей"

**Comment by aurusov** [comment]
> Имеете ввиду главную страницу?

Нет, одну из двух
- http://jenkins.raox.rk9.bmstu.ru/job/raox-rcptt/
- http://jenkins.raox.rk9.bmstu.ru/job/raox-rcptt/54/console

**Comment by bogachev-pa** [comment]
Выложил лист "Функционал среды разработки моделей" в законченном варианте.

**Comment by aurusov** [comment]
Посмотрел

**Comment by bogachev-pa** [comment]
Добавил лист 15 - результаты работы.

> **Результаты работы. Средства среды разработки моделей. А1**
> Тагда уж Функциональные возможности среды разработки

Исправил.

**Comment by aurusov** [comment]
Посмотрел.

Смотрю, ты увеличил Диаграмму пакетов до А1 ? Насчитал 11.5 x А1. Будешь увеличивать размер какому-нибудь листу или планируешь новый ?

**Comment by bogachev-pa** [comment]
> Смотрю, ты увеличил Диаграмму пакетов до А1 ?

Не увеличивал, так и была.

> Насчитал 11.5 x А1. Будешь увеличивать размер какому-нибудь листу или планируешь новый ?

Я просчитался, думал, что все уже готовы.
Есть вариант сделать либо диаграмму активности, описывающую алгоритм симулятора на А2. Я этот алгоритм исправлял, но рассказать про это в докладе у меня времени не будет.
Можно тогда увеличить (8) диаграмму активности валидации стандартных методов модели. Она очень плотно упакована сейчас, чтобы уместилась в А2. Кажется, на А1 тоже будет хорошо смотреться.

Буду делать второе сейчас.

**Comment by bogachev-pa** [comment]
Увеличил диаграмму активности валидации стандартных методов модели до А1.

**Comment by bogachev-pa** [comment]
Поправил лист 12 (тестирование) и лист 15 (результаты работы).

**Comment by bogachev-pa** [comment]
Добавил штампы.

**Comment by aurusov** [comment]
> Не увеличивал, так и была.

Я своими руками переправлял её формат у себя в списке листов. И называлась она Диаграммой компонентов. Вот даже в истории есть https://github.com/bogachev-pa/bogachev-pa.github.io/issues/3#issuecomment-226989396

**Comment by aurusov** [comment]
> Увеличил диаграмму активности валидации стандартных методов модели до А1.

ну ok

**Comment by bogachev-pa** [comment]
> Я своими руками переправлял её формат у себя в списке листов. И называлась она Диаграммой компонентов. 

Понял. Значит, я хоть и сделал сразу А1, но неправильно написал в таске.

**Comment by aurusov** [comment]
Говорят, аннотация должна быть на отдельном листе. https://github.com/timyrka67/timyrka67.github.io/issues/1#issue-157951681

**Comment by bogachev-pa** [comment]
> Говорят, аннотация должна быть на отдельном листе. timyrka67/timyrka67.github.io#1 (comment)

Аннотация должна быть и в самой записке, и отдельным файлом. При этом отдельным файлом она идет с указанием автора проекта, темы проекта и с подписью руководителя.
Выложил ее тоже.

**Comment by aurusov** [comment]
Содержимое тоже самое, что в записке ?

**Comment by bogachev-pa** [comment]
Да.

**Comment by bogachev-pa** [comment]
Добавил пдф со всеми листами в одном файле.
Добавил исходники.
Добавил архив со всем содержимым, включая исходники.

Вроде все?

**Comment by aurusov** [comment]
- не нашел исходников записки
- есть титлы ?

**Comment by bogachev-pa** [comment]
> не нашел исходников записки

Добавил.

> есть титлы ?

Титлов нет. Печатал в институте, заполнял все от руки.

**Comment by aurusov** [comment]
Выложил, http://raox.ru/?p=1237

**Comment by bogachev-pa** [comment]
Ссылки и превью листов/записки перепутаны.

Еще, пожалуйста, исправьте букву "ё" на "е" в моей фамилии.

**Comment by aurusov** [comment]
Все исправил. Но мне казалось, раньше ты специально хотел `ё`. Нет ?

**Comment by bogachev-pa** [comment]
Нет, как раз наоборот.
Спасибо.
